# Generated by Django 4.2.3 on 2023-07-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marketing_promotion',
            new_name='preco_marketing_promocional',
        ),
    ]
