# Generated by Django 4.2.3 on 2023-07-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='is_published',
        ),
    ]
