estados = (
    ('AC','Acre'),
    ('PA','Pará'),
    ('RO','Rondônia'),
    ('RR','Roraima'),
    ('TO','Tocatins'),
    ('MA','Maranhâo'),
    ('PB','Paraíba'),
    ('PE','Pernambuco'),
    ('PI','Piauí'),
    ('RN','Rio Grande do Norte'),
    ('SE','Sergipe'),
    ('GO','Goiás'),
    ('MS','Mato Grosso do Sul'),
    ('MT','Mato Grosso'),
    ('ES','Espírito Santo'),
    ('MG','Minas Gerais'),
    ('RJ','Rio de Janeiro'),
    ('SP','São Paulo'),
    ('RS','Rio Grande do Sul'),
    ('SC','Santa Catarina'),
    ('AM','Amazonas'),
    ('AP','Amapá'),
    ('AL','Alagoas'),
    ('BA','Bahia'),
    ('CE','Ceará'),
    ('PR','Paraná'),
)